### ISSUE TITLE
ZeroInflated distribution

### ISSUE THREAD

**Issue by trungnt13** [chgroenbech/scVAE#4]
In the implementation of `ZeroInflated` distribution [link](https://github.com/chgroenbech/scVAE/blob/5dc15ea7ef72ddc7c93f58c7b2bbc428ed250633/distributions/zero_inflated.py#L108)

```python
 if not isinstance(dist, distribution.Distribution):
      raise TypeError(
          "dist must be a Distribution instance"
          " but saw: %s" % dist)
```

Since all distribution classes have been switched to use tensorflow_probability Distribution, this TypeError happened inappropriately

Secondly, there is Exception when I try sampling from the ZeroInflated

```
Traceback (most recent call last):
  File "./main.py", line 1026, in <module>
    main(**vars(arguments))
  File "./main.py", line 269, in main
    results_directory = results_directory
  File "/data1/libs/scVAE/models/variational_autoencoder.py", line 203, in __init__
    self.model_graph()
  File "/data1/libs/scVAE/models/variational_autoencoder.py", line 680, in model_graph
    self.p_x_given_z.sample()
  File "/data1/libs/miniconda3/envs/ai/lib/python3.5/site-packages/tensorflow/python/ops/distributions/distribution.py", line 766, in sample
    return self._call_sample_n(sample_shape, seed, name)
  File "/data1/libs/miniconda3/envs/ai/lib/python3.5/site-packages/tensorflow/python/ops/distributions/distribution.py", line 745, in _call_sample_n
    samples = self._sample_n(n, seed, **kwargs)
  File "/data1/libs/scVAE/distributions/zero_inflated.py", line 206, in _sample_n
    pi_samples = self.pi.sample(n, seed=seed)
AttributeError: 'Tensor' object has no attribute 'sample
```

This is the description of my ZeroInflated distribution `parameters`:
```
p_x_given_z: tfp.distributions.ZeroInflated("X_TILDE/ZeroInflated_1/", batch_shape=(?, 32738), event_shape=(), dtype=float32)
   allow_nan_stats : True
   dist : tfp.distributions.NegativeBinomial("X_TILDE/NegativeBinomial/", batch_shape=(?, 32738), event_shape=(), dtype=float32)
   name : ZeroInflated
   pi : Tensor("X_TILDE/PI/clip_by_value:0", shape=(?, 32738), dtype=float32)
   validate_args : False
```

The command I used to run:
```bash
./main.py -i 10x-PBMC-PP -m VAE -r zero_inflated_negative_binomial -l 100 -H 101 102 -e 500 --decomposition-methods pca tsne
```

Could you suggest some fix for the issue? 
might be some inconsistent in my environment ?

Best Regards,
TrungNT

**Comment by chgroenbech** [comment]
The `ZeroInflated` and the `Catagorized` distributions now support of distributions from TensorFlow Probability library.

The code for sampling the `ZeroInflated` distribution was never implemented correctly, since it was never used. It has been removed together with other unnecessary and outdated distribution classes and functions.
