### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'points_to_pixels'

### ISSUE THREAD

**Issue by bkaczkowski** [chgroenbech/scVAE#5]
Hi,
I got the following error while running the first example
(main.py -i 10x-PBMC-PP -m GMVAE -r negative_binomial -l 100 -H 100 100 -e 500 --decomposition-methods pca tsne)

'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points.
Traceback (most recent call last):
  File "main.py", line 1260, in <module>
    main(**vars(arguments))
  File "main.py", line 352, in main
    temporary_log_directory = temporary_log_directory
  File "/Users/bogumil/projects/leukemia/scVAE_analysis/scVAE/models/gaussian_mixture_variational_autoencoder.py", line 2113, in train
    results_directory = self.base_results_directory
  File "/Users/bogumil/projects/leukemia/scVAE_analysis/scVAE/analysis.py", line 702, in analyseIntermediateResults
    results_directory = results_directory)
  File "/Users/bogumil/projects/leukemia/scVAE_analysis/scVAE/analysis.py", line 5101, in saveFigure
    adjustFigureForLegend(figure)
  File "/Users/bogumil/projects/leukemia/scVAE_analysis/scVAE/analysis.py", line 5145, in adjustFigureForLegend
    legend_size = legend.get_window_extent()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/legend.py", line 988, in get_window_extent
    return self._legend_box.get_window_extent(renderer=renderer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/offsetbox.py", line 250, in get_window_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/offsetbox.py", line 360, in get_extent_offsets
    dpicor = renderer.points_to_pixels(1.)
AttributeError: 'NoneType' object has no attribute 'points_to_pixels'

**Comment by chgroenbech** [comment]
I can’t reproduce the error. The tool has just been updated to work with the most recent stable versions of its dependencies, so see if you get the same error now (with updated packages). If you do, please report your setup.

**Comment by bkaczkowski** [comment]
I just made a clean install of Python 3.6.6 installed on a mac (macOS Mojave 10.14.2) and re-installed packages. The problem seem to come from "matplotlib" , I have matplotlib-3.0.2 installed, when it tries to plot:
_Plotting learning curves.
Learning curves plotted and saved (1.46 s).
Plotting latent validation set with centroids for epoch 1.
Decomposing latent validation set using PCA.
Latent validation set decomposed (116 ms).
Traceback (most recent call last):
  File "./main.py", line 1267, in <module>
......
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/offsetbox.py", line 360, in get_extent_offsets
    dpicor = renderer.points_to_pixels(1.)_

**Comment by chgroenbech** [comment]
I was able to reproduce the error by using the `macosx` backend for matplotlib, and the latest commit (https://github.com/chgroenbech/scVAE/commit/9522ea86f0c0d9e78c2ae17ad605ee3b10f13025) should fix it.

**Comment by bkaczkowski** [comment]
It works now.
